//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meets.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Meets.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accsess Denied.
        /// </summary>
        public static string AccsessDenied {
            get {
                return ResourceManager.GetString("AccsessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активно.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Now.
        /// </summary>
        public static string AddCart {
            get {
                return ResourceManager.GetString("AddCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered.
        /// </summary>
        public static string AddedCart {
            get {
                return ResourceManager.GetString("AddedCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Rooms.
        /// </summary>
        public static string AllCourses {
            get {
                return ResourceManager.GetString("AllCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Courses By.
        /// </summary>
        public static string AllCoursesBy {
            get {
                return ResourceManager.GetString("AllCoursesBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Memberships.
        /// </summary>
        public static string AllMemberships {
            get {
                return ResourceManager.GetString("AllMemberships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Orders.
        /// </summary>
        public static string AllOrders {
            get {
                return ResourceManager.GetString("AllOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity.
        /// </summary>
        public static string Capacity {
            get {
                return ResourceManager.GetString("Capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to watch this entire course?.
        /// </summary>
        public static string CheckMess1 {
            get {
                return ResourceManager.GetString("CheckMess1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Become a membership or buy this course to watch this entire course..
        /// </summary>
        public static string CheckMess2 {
            get {
                return ResourceManager.GetString("CheckMess2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Out With.
        /// </summary>
        public static string CheckOutWith {
            get {
                return ResourceManager.GetString("CheckOutWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contents.
        /// </summary>
        public static string Contents {
            get {
                return ResourceManager.GetString("Contents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CourseByCategory.
        /// </summary>
        public static string CourseByCategory {
            get {
                return ResourceManager.GetString("CourseByCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CourseByLatest.
        /// </summary>
        public static string CourseByLatest {
            get {
                return ResourceManager.GetString("CourseByLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CourseByLatestParent.
        /// </summary>
        public static string CourseByLatestParent {
            get {
                return ResourceManager.GetString("CourseByLatestParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CourseByNew.
        /// </summary>
        public static string CourseByNew {
            get {
                return ResourceManager.GetString("CourseByNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CourseByOldest.
        /// </summary>
        public static string CourseByOldest {
            get {
                return ResourceManager.GetString("CourseByOldest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CourseByOldestParent.
        /// </summary>
        public static string CourseByOldestParent {
            get {
                return ResourceManager.GetString("CourseByOldestParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CourseByParentCategory.
        /// </summary>
        public static string CourseByParentCategory {
            get {
                return ResourceManager.GetString("CourseByParentCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CourseByTopOrder.
        /// </summary>
        public static string CourseByTopOrder {
            get {
                return ResourceManager.GetString("CourseByTopOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CourseByTopRatings.
        /// </summary>
        public static string CourseByTopRatings {
            get {
                return ResourceManager.GetString("CourseByTopRatings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CourseByTopViews.
        /// </summary>
        public static string CourseByTopViews {
            get {
                return ResourceManager.GetString("CourseByTopViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rooms.
        /// </summary>
        public static string Courses {
            get {
                return ResourceManager.GetString("Courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meetting Booking.
        /// </summary>
        public static string CoursesOnline {
            get {
                return ResourceManager.GetString("CoursesOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date:.
        /// </summary>
        public static string CreationDate {
            get {
                return ResourceManager.GetString("CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EventId.
        /// </summary>
        public static string EventId {
            get {
                return ResourceManager.GetString("EventId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expires.
        /// </summary>
        public static string Expires {
            get {
                return ResourceManager.GetString("Expires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeMale.
        /// </summary>
        public static string FeMale {
            get {
                return ResourceManager.GetString("FeMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstName:.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIClouds. All rights reserved..
        /// </summary>
        public static string FooterCopyright {
            get {
                return ResourceManager.GetString("FooterCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free &amp; Expert Teachers.
        /// </summary>
        public static string FreeExpertTeachers {
            get {
                return ResourceManager.GetString("FreeExpertTeachers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn from industry experts who are passionate about teaching..
        /// </summary>
        public static string FreeExpertTeachersDes {
            get {
                return ResourceManager.GetString("FreeExpertTeachersDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Course has been register..
        /// </summary>
        public static string HasAddCart {
            get {
                return ResourceManager.GetString("HasAddCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        public static string here {
            get {
                return ResourceManager.GetString("here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не активно.
        /// </summary>
        public static string InActive {
            get {
                return ResourceManager.GetString("InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect account!.
        /// </summary>
        public static string IncorrectAccount {
            get {
                return ResourceManager.GetString("IncorrectAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        public static string inn {
            get {
                return ResourceManager.GetString("inn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity:.
        /// </summary>
        public static string Instructor {
            get {
                return ResourceManager.GetString("Instructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructor Information.
        /// </summary>
        public static string InstructorInformation {
            get {
                return ResourceManager.GetString("InstructorInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joined this course to the .
        /// </summary>
        public static string JoinedTo {
            get {
                return ResourceManager.GetString("JoinedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastName:.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest.
        /// </summary>
        public static string Latest {
            get {
                return ResourceManager.GetString("Latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn Anywhere.
        /// </summary>
        public static string LearnAnywhere {
            get {
                return ResourceManager.GetString("LearnAnywhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch between your computer, tablet, or mobile device..
        /// </summary>
        public static string LearnAnywhereDes {
            get {
                return ResourceManager.GetString("LearnAnywhereDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn More.
        /// </summary>
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave a Comment:.
        /// </summary>
        public static string LeaveComment {
            get {
                return ResourceManager.GetString("LeaveComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to .
        /// </summary>
        public static string LoginTo {
            get {
                return ResourceManager.GetString("LoginTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership.
        /// </summary>
        public static string Membership {
            get {
                return ResourceManager.GetString("Membership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages has been sent!.
        /// </summary>
        public static string MessHasBeenSent {
            get {
                return ResourceManager.GetString("MessHasBeenSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        public static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Rooms.
        /// </summary>
        public static string MyCart {
            get {
                return ResourceManager.GetString("MyCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Courses.
        /// </summary>
        public static string NewCourses {
            get {
                return ResourceManager.GetString("NewCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string O {
            get {
                return ResourceManager.GetString("O", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oldest.
        /// </summary>
        public static string Oldest {
            get {
                return ResourceManager.GetString("Oldest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meetting Room Booking.
        /// </summary>
        public static string OnlineLearningMembership {
            get {
                return ResourceManager.GetString("OnlineLearningMembership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option.
        /// </summary>
        public static string Option {
            get {
                return ResourceManager.GetString("Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Information.
        /// </summary>
        public static string OrderInformation {
            get {
                return ResourceManager.GetString("OrderInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderNow.
        /// </summary>
        public static string OrderNow {
            get {
                return ResourceManager.GetString("OrderNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package.
        /// </summary>
        public static string Package {
            get {
                return ResourceManager.GetString("Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join!.
        /// </summary>
        public static string Paid {
            get {
                return ResourceManager.GetString("Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaymentFee:.
        /// </summary>
        public static string PaymentFee {
            get {
                return ResourceManager.GetString("PaymentFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaymentGross:.
        /// </summary>
        public static string PaymentGross {
            get {
                return ResourceManager.GetString("PaymentGross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment History.
        /// </summary>
        public static string PaymentHistory {
            get {
                return ResourceManager.GetString("PaymentHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to people joined this course.
        /// </summary>
        public static string peoplejoined {
            get {
                return ResourceManager.GetString("peoplejoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        public static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 Days.
        /// </summary>
        public static string Peroid2 {
            get {
                return ResourceManager.GetString("Peroid2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        public static string PersonalInformation {
            get {
                return ResourceManager.GetString("PersonalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLACES.
        /// </summary>
        public static string Places {
            get {
                return ResourceManager.GetString("Places", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Sign In.
        /// </summary>
        public static string PleaseSignIn {
            get {
                return ResourceManager.GetString("PleaseSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted on.
        /// </summary>
        public static string Postedon {
            get {
                return ResourceManager.GetString("Postedon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating:.
        /// </summary>
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8-20 character at least 1 Alphabet, 1 Number and No Special Character.
        /// </summary>
        public static string RegexPass {
            get {
                return ResourceManager.GetString("RegexPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register now to receive incentives..
        /// </summary>
        public static string Registernow {
            get {
                return ResourceManager.GetString("Registernow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Success!.
        /// </summary>
        public static string RegisterSuccess {
            get {
                return ResourceManager.GetString("RegisterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report from Course detail.
        /// </summary>
        public static string ReportFromCourseDetail {
            get {
                return ResourceManager.GetString("ReportFromCourseDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing.
        /// </summary>
        public static string Showing {
            get {
                return ResourceManager.GetString("Showing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up Now.
        /// </summary>
        public static string SignUpNow {
            get {
                return ResourceManager.GetString("SignUpNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort By.
        /// </summary>
        public static string SortBy {
            get {
                return ResourceManager.GetString("SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  star.
        /// </summary>
        public static string Star {
            get {
                return ResourceManager.GetString("Star", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders has been send success! Admin will contact you in the shortest time!.
        /// </summary>
        public static string SuccessMess {
            get {
                return ResourceManager.GetString("SuccessMess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks!.
        /// </summary>
        public static string Thanks {
            get {
                return ResourceManager.GetString("Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for buying. Click.
        /// </summary>
        public static string Thanksforbuying {
            get {
                return ResourceManager.GetString("Thanksforbuying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  to .
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to continue..
        /// </summary>
        public static string tocontinue {
            get {
                return ResourceManager.GetString("tocontinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Buy.
        /// </summary>
        public static string TopBuy {
            get {
                return ResourceManager.GetString("TopBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Course.
        /// </summary>
        public static string TopCourse {
            get {
                return ResourceManager.GetString("TopCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Ratings.
        /// </summary>
        public static string TopRatings {
            get {
                return ResourceManager.GetString("TopRatings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Trends.
        /// </summary>
        public static string TopTrends {
            get {
                return ResourceManager.GetString("TopTrends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Views.
        /// </summary>
        public static string TopViews {
            get {
                return ResourceManager.GetString("TopViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total:.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransactionId:.
        /// </summary>
        public static string TransactionId {
            get {
                return ResourceManager.GetString("TransactionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlimited Access.
        /// </summary>
        public static string UnlimitedAccess {
            get {
                return ResourceManager.GetString("UnlimitedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose what you&apos;d like to learn from our extensive subscription library..
        /// </summary>
        public static string UnlimitedAccessDes {
            get {
                return ResourceManager.GetString("UnlimitedAccessDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Information.
        /// </summary>
        public static string UpdateInformation {
            get {
                return ResourceManager.GetString("UpdateInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username already exists!.
        /// </summary>
        public static string UserExists {
            get {
                return ResourceManager.GetString("UserExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or Password incorrect!.
        /// </summary>
        public static string UserOrPassIncorrect {
            get {
                return ResourceManager.GetString("UserOrPassIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age restriction from.
        /// </summary>
        public static string ValidAge {
            get {
                return ResourceManager.GetString("ValidAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title or Description can&apos;t empty!.
        /// </summary>
        public static string ValidDesc {
            get {
                return ResourceManager.GetString("ValidDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Detail.
        /// </summary>
        public static string ViewDetail {
            get {
                return ResourceManager.GetString("ViewDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View more comments.
        /// </summary>
        public static string Viewmorecmt {
            get {
                return ResourceManager.GetString("Viewmorecmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views:.
        /// </summary>
        public static string Views {
            get {
                return ResourceManager.GetString("Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Meetting Room Booking.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Are Not Permission!.
        /// </summary>
        public static string YouAreNotPermission {
            get {
                return ResourceManager.GetString("YouAreNotPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You vote: .
        /// </summary>
        public static string YouVote {
            get {
                return ResourceManager.GetString("YouVote", resourceCulture);
            }
        }
    }
}
